language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:xav0989/libconfig
  - sudo apt-get update -qq
  - sudo apt-get install --allow-unauthenticated -qq pandoc python libconfig-dev

script:
  - cmake .
  - make all
  - make check
  - mkdir target_dir
  - DESTDIR=target_dir make install
