language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install --allow-unauthenticated -qq qt4-qmake
  - pip install pep8

script:
  - pep8 bear
  - cmake . -DCPACK_GENERATOR="TGZ;DEB"
  - make all
  - make check
  - mkdir target_dir
  - DESTDIR=target_dir make install
  - make package

after_success:
  - sudo dpkg -i ./bear-*.deb
