language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq pandoc python libconfig8-dev

script:
  - cmake .
  - make all
  - make check
  - mkdir target_dir
  - DESTDIR=target_dir make install
