language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:xav0989/libconfig
  - sudo apt-get update -qq

install:
  - sudo apt-get install --allow-unauthenticated -qq python libconfig-dev

script:
  - cmake . -DCPACK_GENERATOR="TGZ;DEB"
  - make all
  - make check
  - mkdir target_dir
  - DESTDIR=target_dir make install
  - make package

after_success:
  - sudo dpkg -i ./bear-*.deb
